name: Build golang-set CI-CD
run-name: Running CI-CD for golang-set
on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum

      - name: Mod Tidy
        run: go mod tidy

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v2.1.6

      - name: Build
        run: go build ./...

      - name: Test
        run: make test

      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARQUBE_INTEGRATION_TOKEN }} # this is available in Collibra GH organization
        with:
          args: >
            -Dsonar.host.url=https://sonarqube.collibra.com/
            -Dsonar.projectKey=go-set
            -Dsonar.sources=.
            -Dsonar.exclusions=**/*_test.go,./.github/**
            -Dsonar.tests=.
            -Dsonar.test.inclusions=**/*_test.go
            -Dsonar.scm.provider=git
            -Dsonar.go.coverage.reportPaths=coverage.txt
            -Dsonar.javascript.lcov.reportPaths=path-to-lcov.info