name: Build golang-set CI-CD
run-name: Running CI-CD for golang-set
on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum

      - name: Mod Tidy
        run: go mod tidy

      - name: Lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9  # v8
        with:
          version: v2.4.0

      - name: Build
        run: go build ./...

      - name: Test
        run: make test

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@2f77a1ec69fb1d595b06f35ab27e97605bdef703  # v5
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_PUBLIC_API_KEY }}
          SONAR_HOST_URL: https://sonarqube.collibra.dev
        with:
          args: >
            -Dsonar.pullrequest.github.repository=collibra/go-set

#      - name: SonarQube Quality Gate
#        uses: sonarsource/sonarqube-quality-gate-action@v1.1.0
#        timeout-minutes: 10
#        continue-on-error: true
#        env:
#          SONAR_TOKEN: ${{ secrets.SONARQUBE_PUBLIC_API_KEY }}
#          SONAR_HOST_URL: https://sonarqube.collibra.dev

      - name: FOSSA Scan
        uses: fossas/fossa-action@ff70fe9fe17cbd2040648f1c45e8ec4e4884dcf3  # v1
        with:
          api-key: ${{ secrets.FOSSA_PUBLIC_API_KEY }}
